version: "3.7"
services:
  mysql57:
    image: mysql:5.7
    ports:
      - 33066:3306
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
      TZ: Asia/Tokyo
