name: ci
on:
  pull_request:
    # paths:
    #   - '**.go'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: cache
        id: cache
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Generate Vendor
        if: steps.cache.outputs.cache-hit != 'true'
        run: go mod vendor
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: ./
  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: build
    - name: lint
      working-directory: build
      run: make lint
  test:
    name: test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: build
    - name: DB Up
      working-directory: build
      run: make up
    - name: DB Wait
      working-directory: build
      run: make wait
    - name: test
      working-directory: build
      run: make test
